# SonarCloud configuration

# Exclude specific directories from analysis
sonar.exclusions=storage/**,client/node_modules/**,vendor/**,binaries/**,cache/**

# Ignore Cognitive Complexity (S3776) for Go files
sonar.issue.ignore.multicriteria=e1,e2

sonar.issue.ignore.multicriteria.e1.ruleKey=go:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.go

# Ignore String Literal Duplication (S1192) for Go files
sonar.issue.ignore.multicriteria.e2.ruleKey=go:S1192
sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.go
